name = "JDQMCFramework"
uuid = "72315111-4c7c-4639-8a62-af4b2dda42e0"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.4.3"

[deps]
Checkerboard = "b297549e-c8cb-44e5-9c33-b7e2667db6fc"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StableLinearAlgebra = "7d06c537-f8ff-4c22-91e1-ce4088e3cfd7"

[compat]
StableLinearAlgebra = "1.3"
FastLapackInterface = "1.2"
Checkerboard = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
