name = "JDQMCFramework"
uuid = "72315111-4c7c-4639-8a62-af4b2dda42e0"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
